language: cpp
compiler: gcc

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install gcc-7 g++-7 libopenmpi-dev libcgal-dev libsparsehash-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90

script:
  - mkdir build && cd build && cmake .. && make 
